[package]
name = "procstat"
version = "0.1.0"
authors = ["Emil Hammarström <emil.a.hammarstrom@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1.1.2"
lazy_static = "1.3.0"
serde = { version = "1.0.89", features = ["derive"] }
serde_json = "1.0.39"
nom = "4.2.2"
ws = "*"
